### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by cicerojones** [kisp/musicxml-pwgl#2]
Hi,

Assuming there's a reason for the 404 error on http://sprotte.org/perm/musicxml-pwgl.html, which is also linked from the PWGL Downloads page. 

- Perhaps the library has been superseded? 
- Or should we just expect to clone from Github and install manually?

Any help would be greatly appreciated.

Thanks for your great work!

**Comment by kisp** [comment]
Hi,

thanks for the report!

Please go to https://github.com/kisp/musicxml-pwgl and check if the updated README.md works for you.

The content on sprotte.org has been removed, so that's the reason for the 404.

There is some preprocessing done to the files, so a clone from github will not work. The releases page has now tarballs to download where the preprocessing has been done.

HTH

Best
Kilian

**Comment by cicerojones** [comment]
Great, thank you!

I hadn't used PWGL for a while so it took me a few minutes to remember how to load libraries (apparently OMPW is a dependency, which library is itself non-obviously ensconced in the libraries on [the JBS website](http://www.baboni-schilingi.com/index.php/research), in case that helps anybody else who comes here). 

As thorough as the PWGL tutorial is (and as responsive as the mailing list is), I still wish there were more robust blogging/documentation from the amazing PWGL community! For example, a simple change on a true Wiki (the currently listed "Wiki" on the [Support page](http://www2.siba.fi/PWGL/support.html) takes you to someone's personal profile) could now redirect visitors of the PWGL Downloads page to the proper place. Feel free to add any suggestions on where to look for more info. 

Again, thanks for your work 👍
